# ./.tmuxinator.yml

name: blueclaw

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

windows:
  - editor:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim
        - clear
        - clear
  - work:
  - sandbox:
